token_ttl: 48h
secret: "<your-secret>"
app:
  port: 8080
  addr: "0.0.0.0"
postgres:
  addr: "storage"
  port: 5432
  user: "postgres"
  password: "postgres"
  db: "sharing_machines"
# settings for microcontroller (arduino)
mc:
  request_timeout: 1s
